global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "lstm-stock-api"

    metrics_path: /metrics

    static_configs:

      - targets:
          - lstm-stock-predictor-api.onrender.com

          # producao
          # - sua-api.onrender.com



===